 import { fromEvent,Observable } from 'https://dev.jspm.io/rxjs@6/_esm2015';

        const fruits = JSON.parse("[\"Abiu\",\"Açaí\",\"Acerola\",\"Ackee\",\"African cucumber\",\"Apple\",\"Apricot\",\"Avocado\",\"Banana\",\"Bilberry\",\"Blackberry\",\"Blackcurrant\",\"Black sapote\",\"Blueberry\",\"Boysenberry\",\"Breadfruit\",\"Buddha's hand (fingered citron)\",\"Cactus pear\",\"Canistel\",\"Cempedak\",\"Cherimoya (Custard Apple)\",\"Cherry\",\"Chico fruit\",\"Cloudberry\",\"Coco De Mer\",\"Coconut\",\"Crab apple\",\"Cranberry\",\"Currant\",\"Damson\",\"Date\",\"Dragonfruit (or Pitaya)\",\"Durian\",\"Egg Fruit\",\"Elderberry\",\"Feijoa\",\"Fig\",\"Finger Lime (or Caviar Lime)\",\"Goji berry\",\"Gooseberry\",\"Grape\",\"Raisin\",\"Grapefruit\",\"Grewia asiatica (phalsa or falsa)\",\"Guava\",\"Hala Fruit\",\"Honeyberry\",\"Huckleberry\",\"Jabuticaba\",\"Jackfruit\",\"Jambul\",\"Japanese plum\",\"Jostaberry\",\"Jujube\",\"Juniper berry\",\"Kaffir Lime\",\"Kiwano (horned melon)\",\"Kiwifruit\",\"Kumquat\",\"Lemon\",\"Lime\",\"Loganberry\",\"Longan\",\"Loquat\",\"Lulo\",\"Lychee\",\"Magellan Barberry\",\"Mamey Apple\",\"Mamey Sapote\",\"Mango\",\"Mangosteen\",\"Marionberry\",\"Melon\",\"Cantaloupe\",\"Galia melon\",\"Honeydew\",\"Mouse melon\",\"Musk melon\",\"Watermelon\",\"Miracle fruit\",\"Monstera deliciosa\",\"Mulberry\",\"Nance\",\"Nectarine\",\"Orange\",\"Blood orange\",\"Clementine\",\"Mandarine\",\"Tangerine\",\"Papaya\",\"Passionfruit\",\"Peach\",\"Pear\",\"Persimmon\",\"Plantain\",\"Plum\",\"Prune (dried plum)\",\"Pineapple\",\"Pineberry\",\"Plumcot (or Pluot)\",\"Pomegranate\",\"Pomelo\",\"Purple mangosteen\",\"Quince\",\"Raspberry\",\"Salmonberry\",\"Rambutan (or Mamin Chino)\",\"Redcurrant\",\"Rose apple\",\"Salal berry\",\"Salak\",\"Satsuma\",\"Shine Muscat or Vitis Vinifera\",\"Sloe or Hawthorn Berry\",\"Soursop\",\"Star apple\",\"Star fruit\",\"Strawberry\",\"Surinam cherry\",\"Tamarillo\",\"Tamarind\",\"Tangelo\",\"Tayberry\",\"Tomato\",\"Ugli fruit\",\"White currant\",\"White sapote\",\"Yuzu\",\"Bell pepper\",\"Chile pepper\",\"Corn kernel\",\"Cucumber\",\"Eggplant\",\"Jalapeño\",\"Olive\",\"Pea\",\"Pumpkin\",\"Squash\",\"Tomato\",\"Zucchini\"]");
        // Refers to the query box from the search query is to be fetched.
        const queryBox = document.getElementById('query');
        // Refers to the list of suggestions generated by VanillaJS
        const vanillaSuggestions = document.getElementById('vanillaSuggestions');
        // Refers to the list of suggestions generated by RxJS
        const rxjsSuggestions = document.getElementById('rxjsSuggestions');
        
        // Refers to the display unit which displays
        // the number of time the filter function got called. 
        const rxjsFilterCountBox = document.getElementById('rxJSFilterCount');
        const vanillaJSFilterCountBox = document.getElementById('vanillaJSFilterCount');
        
        // Count of How many times the filter function gets called
        // in the VanillaJS
        let vanillaJSFilterCount = 0;
        // Count of How many times the filter function gets called
        // in the RxJS Script
        let rxJSFilterCount = 0;
        
        //Using Vanilla JS
        queryBox.addEventListener('input', () => {
            ++vanillaJSFilterCount;
            const suggestedFruits = fruits.filter(f => f.startsWith(queryBox.value));
            vanillaSuggestions.innerHTML = "";
            suggestedFruits.forEach(fruit => {
                const fruitEl = document.createElement('li');
                fruitEl.innerText = fruit;
                vanillaSuggestions.appendChild(fruitEl);
            });
            vanillaJSFilterCountBox.innerText = vanillaJSFilterCount;
        });
        
        // Using RxJS code here...
const obser=(fromEvent(queryBox,'input'));
const observer={
        next:(data)=>{
            setTimeout(()=>{
            ++rxJSFilterCount;
            console.log(data);
            rxjsFilterCountBox.innerText=rxJSFilterCount;
            const suggestedFruits = fruits.filter(f => f.startsWith(queryBox.value));
            rxjsSuggestions.innerHTML = "";
            suggestedFruits.forEach(fruit => {
                const fruitEl = document.createElement('li');
                fruitEl.innerText = fruit;
                rxjsSuggestions.appendChild(fruitEl);},1000);});
            },
        error:(err)=>{console.log(err)},
        complete:()=>{console.log("Complete")}
}
obser.subscribe(observer);




// const observer={
//     next:(data)=>{
//     let data2=data;
//     setTimeout((data2)=>{ ++rxJSFilterCount;
//         console.log(data2);
//         rxjsFilterCountBox.innerText=rxJSFilterCount;
//        },3000)},
//    error:(err)=>{console.log(err)},
//    complete:()=>{console.log("Complete")}

  
// }
// observable.subscribe(observer)

// const observable = new Observable(subscriber => {
//     subscriber.next(1);
//     subscriber.next(2);
//     subscriber.next(3);
   
//     setTimeout(() => {
//       subscriber.next(4);
//       subscriber.complete();
//     }, 1000);
  



// Rx.Observable.fromEvent(document.getElementById('query'),'input')
//         .map(v => v.target.value)
//         .subscribe(sv=>{
//             rxJSFilterCount++;
//             rxjsSuggestions.innerText='';
//            fruits.filter(fv=>fv.startsWith(sv)).forEach(fev=>{
//                var a=document.createElement('li');
//                a.innerText=fev;
//                rxjsSuggestions.appendChild(a);
//                if(sv==''){
//                 rxjsSuggestions.innerText='';
//             };





